# Generated by Django 4.1.2 on 2022-11-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('date_upload', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('done', models.CharField(blank=True, max_length=10, null=True)),
                ('modality', models.CharField(blank=True, max_length=16, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('Не размечен', 'Не размечен'), ('Отклонён', 'Отклонён'), ('В процессе разметки', 'В процессе разметки'), ('Размечен', 'Размечен')], default='НР', max_length=20)),
                ('instance_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_upload'],
            },
        ),
    ]
