# Generated by Django 4.1.2 on 2022-11-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_upload', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('done', models.DateField(blank=True, null=True)),
                ('modality', models.CharField(max_length=16, null=True)),
                ('state', models.CharField(choices=[('HP', 'Не размечен'), ('ОТ', 'Отклонён'), ('ВПР', 'В процессе разметки '), ('Р', 'Размечен')], default='НР', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
