# Generated by Django 4.1.2 on 2022-11-02 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['date_upload']},
        ),
        migrations.AddField(
            model_name='study',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='date_upload',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
