# Generated by Django 3.2.16 on 2022-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuploadedfile',
            name='dirname',
        ),
        migrations.RemoveField(
            model_name='authuploadedfile',
            name='name',
        ),
    ]
