# Generated by Django 4.1.2 on 2022-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
