# Generated by Django 3.2.16 on 2022-10-24 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20221024_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuploadedfile',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
