# Generated by Django 4.1.2 on 2022-11-02 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_study_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
