# Generated by Django 4.1.2 on 2022-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
